### ISSUE TITLE
Encoder connector in uBridge

### ISSUE THREAD

**Issue by rbonghi** [officinerobotiche/uNAVPCB#1]
I would like to connect encoders in same uBridge board, this is possible?

I told with @Marnic @katodo on the meeting.

**Comment by Marnic** [comment]
just added in sch file, @katodo now work on the board

**Comment by rbonghi** [comment]
:+1:

**Comment by katodo** [comment]
Ok, tomorrow I can check scheme...

**Comment by katodo** [comment]
With jumper on I/O7 and I/O8  pin I can use this pin as GND for encoder attached directly on uNAV44.
This issue can be reopened on uBridge Repo.
