### ISSUE TITLE
Analog input analisys

### ISSUE THREAD

**Issue by katodo** [officinerobotiche/uNAVPCB#3]
In uNav board there are 4 inputs reserved for analog operation.

In my idea all input must be "general porpouse" with a 0-3,3V input range and a medium high input impedance.

I've remove OA in board because pic input is also a "semi-general-porpouse" input and Operational Amplifier-related section is very conditioned by type of measure:

Measure of current in L'298 like shunt resistor require a gain depending by current and shunt resistor. For example with 2A on 0,1 Ohm resistor I need a gain of 16,5 to obtain 0-3,3 V range, but with a different driver driver like Allegro A4950 I need a 3,7 gain ( 3,5A and 0,25 Ohm resistor )... In this case OA section is not required and is only redundant.
In other bridge with hall-effect current sensor IC there are +/-5A +/-10A or bigger full-scale ( 2,5V @ 0A measure ) and a programmable OA can be required for a big accuracy on low current measure.
Also, a filter can be required...

Input for Voltage measure require a different section, I need a voltage divider and a filter depending by type of measured voltage ( input voltage, motor coil voltage etc... )

Besides, measure conditioning mus be near source of current/voltage under test... and in all case input section can't be equal and fixed...

**Comment by guiott** [comment]
In the dsNav version of motor controller (see attached) there is an amplifier with a gain of 1 or 10 selectable by a soldering jumper. That's enough for a L298 h-bridge too, as I've used on Rino. Furthermore there is a minimal low-pass filter to filter out the PWM frequency. Further filtering is achieved via software procedures: using DMA of dsPIC33F ADC you can get 16 samples with no CPU intervention and compute the average after the interrupt trigger.
I agree at all that this can be redundant in many cases and the best solution is to condition the signal where it's generated, but this keep the board more general purpose.

On the other hand a simpler board, with less components, placed on the top layer only, costs less and results more attractive to most of the possible customers.

Is it possible to calculate the cost saving in the simpler solution? I think this is the best parameter to discuss on.

> Il giorno 13/gen/2015, alle ore 08:09, Katodo notifications@github.com ha scritto:
> 
> In uNav board there are 4 inputs reserved for analog operation.
> 
> In my idea all input must be "general porpouse" with a 0-3,3V input range and a medium high input impedance.
> 
> I've remove OA in board because pic input is also a "semi-general-porpouse" input and Operational Amplifier-related section is very conditioned by type of measure:
> 
> Measure of current in L'298 like shunt resistor require a gain depending by current and shunt resistor. For example with 2A on 0,1 Ohm resistor I need a gain of 16,5 to obtain 0-3,3 V range, but with a different driver driver like Allegro A4950 I need a 3,7 gain ( 3,5A and 0,25 Ohm resistor )... In this case OA section is not required and is only redundant.
> In other bridge with hall-effect current sensor IC there are +/-5A +/-10A or bigger full-scale ( 2,5V @ 0A measure ) and a programmable OA can be required for a big accuracy on low current measure.
> Also, a filter can be required...
> 
> Input for Voltage measure require a different section, I need a voltage divider and a filter depending by type of measured voltage ( input voltage, motor coil voltage etc... )
> 
> Besides, measure conditioning mus be near source of current/voltage under test... and in all case input section can't be equal and fixed...
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/officinerobotiche/uNAVPCB/issues/3.

---

http://www.guiott.com/

**Comment by katodo** [comment]
Ok, I'm evaluating this IC:
http://ww1.microchip.com/downloads/en/DeviceDoc/22004b.pdf
http://it.farnell.com/microchip/mcp6g01t-e-ot/amp-select-gain-single-1-mhz-smd/dp/1332148?ost=1332148

Gain is pin-selectable from 1, 10 and 50 value, IC is Rail-ToR-Rail and supplies is 1,8-5V range...
IC is small but I suspect that bottom side wil be needed and filer can't be perfomed in HW... 
Voltage supply can be the same of dsPIC... ad will be the same...

During PCB update I will choose ideal version of IC ( 4pcs 1-channel or 1 IC at 4 ch ).
About 2 side version cost's, there are a lot of thing to be evaluated but in this stage I consider that, if there are some  IC on bottom side of PCB, they can be hand soldered.

@guiott @Marnic @Myzhar @rbonghi @bobboteck  can you "vote" this possible solution ( +1 or -1 )?

**Comment by guiott** [comment]
Like!

> Il giorno 13/gen/2015, alle ore 10:14, Katodo <notifications@github.com <mailto:notifications@github.com>> ha scritto:
> 
> Ok, I'm evaluating this IC:
> http://ww1.microchip.com/downloads/en/DeviceDoc/22004b.pdf http://ww1.microchip.com/downloads/en/DeviceDoc/22004b.pdf
> http://it.farnell.com/microchip/mcp6g01t-e-ot/amp-select-gain-single-1-mhz-smd/dp/1332148?ost=1332148 http://it.farnell.com/microchip/mcp6g01t-e-ot/amp-select-gain-single-1-mhz-smd/dp/1332148?ost=1332148
> Gain is pin-selectable from 1, 10 and 50 value, IC is Rail-ToR-Rail and supplies is 1,8-5V range...
> IC is small but I suspect that bottom side wil be needed and filer can't be perfomed in HW... 
> Voltage supply can be the same of dsPIC... ad will be the same...
> 
> During PCB update I will choose ideal version of IC ( 4pcs 1-channel or 1 IC at 4 ch ).
> About 2 side version cost's, there are a lot of thing to be evaluated but in this stage I consider that, if there are some IC on bottom side of PCB, they can be hand soldered.
> 
> @guiott https://github.com/guiott @Marnic https://github.com/Marnic @Myzhar https://github.com/Myzhar @rbonghi https://github.com/rbonghi @bobboteck https://github.com/bobboteck can you "vote" this possible solution ( +1 or -1 )?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/officinerobotiche/uNAVPCB/issues/3#issuecomment-69715523.

---

http://www.guiott.com/ http://www.guiott.com/

**Comment by Marnic** [comment]
OK
1++

Da: "Katodo" notifications@github.com
A: "officinerobotiche/uNAVPCB" uNAVPCB@noreply.github.com
Cc: "Marnic" marco@fabbrimarco.com
Data: Tue, 13 Jan 2015 01:14:45 -0800
Oggetto: Re: [uNAVPCB] Analog input analisys (#3)

**Comment by rbonghi** [comment]
:+1:

**Comment by bobboteck** [comment]
+1

**Comment by Myzhar** [comment]
+1

2015-01-13 16:28 GMT+01:00 Bobboteck notifications@github.com:

> +1
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/officinerobotiche/uNAVPCB/issues/3#issuecomment-69761423
> .

## 

_Walter "Myzhar" Lucetti_

email myzhar@robot-home.it
web: _www.robot-home.it http://www.robot-home.it/ - www.opencv.it
http://www.opencv.it/_
project:  http://myzharbot.robot-home.it

**Comment by katodo** [comment]
in final revison of scheme I've added OA with configurable GAIN using MCU I/O... I consider closed this issue
