### ISSUE TITLE
Move GND near TX2

### ISSUE THREAD

**Issue by bobboteck** [officinerobotiche/uNAVPCB#5]
Is possible in the BUS connector, move the actual GND near IO5, near the TX2 pin, in place oh IO6?

**Comment by Marnic** [comment]
you think to use two UART? if not, you can make just only one cable TX-RX-GND and if you rotate the cable 180 degrees you have GND-RX-TX so as displaced in the bus connector

**Comment by katodo** [comment]
and, if you use 2 uart, you can use a single cable with a common GND...

Replace a I/O with GND isn't possible in this board, I'm sorry.

  Mauro

2015-01-20 11:06 GMT+01:00 Marnic notifications@github.com:

**Comment by bobboteck** [comment]
@Marnic, Yes use two UART, if you want connect two uNav!

Ok if is not possible, as I said it's only a question "if is possible".
