### ISSUE TITLE
Fourth mount pad

### ISSUE THREAD

**Issue by bobboteck** [officinerobotiche/uNAVPCB#6]
I have see there is only 3 mount pad, but we have four hole. I see also there aren't enough sapce to put it. My question is, tis hole can't be used for mounting the board?

**Comment by katodo** [comment]
3 pad have GND ring and fourth PAD is a simple hole, can be used for PCB fix but must be used with caution ( plastic screw or washer ). In final version I can check a solution...

**Comment by katodo** [comment]
Added... solved :)
